model: 'resnet18'
batch_size: 256
model_params:
  pretrained: false
dataset: 'DataFrameDS' # TODO
data_params:
  md_file: '%p/../rsna-pneumonia/stage_2_train_labels.csv'
  data_file: '%p/../rsna-pneumonia/rsna.npy'
  subset: 1
optim_params:
  lr: 0.01
lr_sched: StepLR
sched_params:
  step_size: 5
  gamma: 0.9
loss: 'CrossEntropyLoss'
optim: 'Adam'
